name: Discord
on:
  pull_request:

  workflow_dispatch:

jobs:
  pr-pipline:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: create .env file
        run: echo "token=${{ secrets.DISCORD_TOKEN }}" > .env

      - name: install dependencies
        uses: ./.github/actions/npm-install

      - name: build env
        shell: bash
        run: npm run test